### ISSUE TITLE
Support for tag file systems

### ISSUE THREAD

**Issue by elbosso** [akkana/pho#6]
Hi, I just got word of this project from your recent blog article. I wanted to ask you if you heard of the niche called tag file systems. If not - maybe look it up. If you find it interesting, you could try to intgrate it with the app? Some links to get you started: 
* https://elbosso.github.io/tag_basierte_dateisysteme.html#content (Its in german because it is in my own blog), 
* https://github.com/StrumentiResistenti/Tagsistant
* https://github.com/oniony/TMSU/wiki
* https://www.tagsistant.net/
* https://www.tagspaces.org/

**Comment by akkana** [comment]
I have occasionally thought about writing something to store tags in the EXIF for each file -- though that would belong more in my metapho project, https://github.com/akkana/metapho (which is in Python, not C), than in pho since all pho does is print out lists of tagged files, it doesn't try to save that info anywhere or categorize it. I started to add that to pho and realized it was really a job that called for separate UI.

Metapho currently saves tag info in files named Tags in each photo directory (so individual files aren't changed). For someone who was running a tagged filesystem, changing the filesystem tags would definitely be a good option there, and certainly cleaner and faster than modifying EXIF.

I don't run a tagged filesystem myself so there's not much motivation for me to put a lot of work into such a change. But if you wanted to contribute patches for metapho to work with tagged filesystems, I'd be very open to that, and would be happy to help you get started. It would probably mostly involve changes to class Tagger in the file metapho/metapho.py, and there would be a good argument for splitting Tagger off into its own file, metapho/tagger.py. File a bug on metapho if you're interested in this.

If you really want it for pho, not metapho, I'm not clear exactly what pho would do with a tagged filesystem since it doesn't save tag info now, just prints out tag numbers. In that case, please give more details here about what you think pho should do with tagging (that's different from what metapho does).

I'm going to close this since I think it probably belongs in the metapho project, but I'm pretty sure you can still comment in closed issues, so if you comment about why it belongs in pho, I'll read it and can reopen the bug.
